#pragma once

/* ESPAgent Global Configuration */

/* Build-time secrets (highest priority, override NVS) */
#if __has_include("espagent_secrets.h")
#include "espagent_secrets.h"
#endif

#ifndef ESPAGENT_SECRET_WIFI_SSID
#define ESPAGENT_SECRET_WIFI_SSID       ""
#endif
#ifndef ESPAGENT_SECRET_WIFI_PASS
#define ESPAGENT_SECRET_WIFI_PASS       ""
#endif
#ifndef ESPAGENT_SECRET_API_KEY
#define ESPAGENT_SECRET_API_KEY         ""
#endif
#ifndef ESPAGENT_SECRET_MODEL
#define ESPAGENT_SECRET_MODEL           ""
#endif
#ifndef ESPAGENT_SECRET_MODEL_PROVIDER
#define ESPAGENT_SECRET_MODEL_PROVIDER  "anthropic"
#endif
#ifndef ESPAGENT_SECRET_PROXY_HOST
#define ESPAGENT_SECRET_PROXY_HOST      ""
#endif
#ifndef ESPAGENT_SECRET_PROXY_PORT
#define ESPAGENT_SECRET_PROXY_PORT      ""
#endif
#ifndef ESPAGENT_SECRET_PROXY_TYPE
#define ESPAGENT_SECRET_PROXY_TYPE      ""
#endif
#ifndef ESPAGENT_SECRET_SEARCH_KEY
#define ESPAGENT_SECRET_SEARCH_KEY      ""
#endif
#ifndef ESPAGENT_SECRET_FEISHU_APP_ID
#define ESPAGENT_SECRET_FEISHU_APP_ID   ""
#endif
#ifndef ESPAGENT_SECRET_FEISHU_APP_SECRET
#define ESPAGENT_SECRET_FEISHU_APP_SECRET ""
#endif
#ifndef ESPAGENT_SECRET_TAVILY_KEY
#define ESPAGENT_SECRET_TAVILY_KEY      ""
#endif
#ifndef ESPAGENT_SECRET_AMAP_KEY
#define ESPAGENT_SECRET_AMAP_KEY        ""
#endif
#ifndef ESPAGENT_SECRET_AMAP_DEFAULT_LOCATION
#define ESPAGENT_SECRET_AMAP_DEFAULT_LOCATION "南京市栖霞区"
#endif
#ifndef ESPAGENT_SECRET_AMAP_DEFAULT_ADCODE
#define ESPAGENT_SECRET_AMAP_DEFAULT_ADCODE "320113"
#endif
#ifndef ESPAGENT_SECRET_WS2812_GPIO
#define ESPAGENT_SECRET_WS2812_GPIO     48
#endif
#ifndef ESPAGENT_SECRET_SGP30_SDA_GPIO
#define ESPAGENT_SECRET_SGP30_SDA_GPIO  14
#endif
#ifndef ESPAGENT_SECRET_SGP30_SCL_GPIO
#define ESPAGENT_SECRET_SGP30_SCL_GPIO  15
#endif
#ifndef ESPAGENT_SECRET_SGP30_I2C_PORT
#define ESPAGENT_SECRET_SGP30_I2C_PORT  1
#endif
#ifndef ESPAGENT_SECRET_SGP30_SCL_HZ
#define ESPAGENT_SECRET_SGP30_SCL_HZ    100000
#endif
#ifndef ESPAGENT_SECRET_MAX98357_BCLK_GPIO
#define ESPAGENT_SECRET_MAX98357_BCLK_GPIO 1
#endif
#ifndef ESPAGENT_SECRET_MAX98357_WS_GPIO
#define ESPAGENT_SECRET_MAX98357_WS_GPIO 2
#endif
#ifndef ESPAGENT_SECRET_MAX98357_DIN_GPIO
#define ESPAGENT_SECRET_MAX98357_DIN_GPIO 3
#endif
#ifndef ESPAGENT_SECRET_MAX98357_SD_GPIO
#define ESPAGENT_SECRET_MAX98357_SD_GPIO (-1)
#endif
#ifndef ESPAGENT_SECRET_MAX98357_I2S_PORT
#define ESPAGENT_SECRET_MAX98357_I2S_PORT 0
#endif
#ifndef ESPAGENT_SECRET_MAX98357_SAMPLE_RATE_HZ
#define ESPAGENT_SECRET_MAX98357_SAMPLE_RATE_HZ 16000
#endif
#ifndef ESPAGENT_SECRET_MAX98357_DEFAULT_TONE_HZ
#define ESPAGENT_SECRET_MAX98357_DEFAULT_TONE_HZ 440
#endif
#ifndef ESPAGENT_SECRET_MAX98357_DEFAULT_DURATION_MS
#define ESPAGENT_SECRET_MAX98357_DEFAULT_DURATION_MS 2000
#endif
#ifndef ESPAGENT_SECRET_MAX98357_DEFAULT_VOLUME_PCT
#define ESPAGENT_SECRET_MAX98357_DEFAULT_VOLUME_PCT 70
#endif
#ifndef ESPAGENT_SECRET_BH1750_SDA_GPIO
#define ESPAGENT_SECRET_BH1750_SDA_GPIO 11
#endif
#ifndef ESPAGENT_SECRET_BH1750_SCL_GPIO
#define ESPAGENT_SECRET_BH1750_SCL_GPIO 12
#endif
#ifndef ESPAGENT_SECRET_BH1750_I2C_PORT
#define ESPAGENT_SECRET_BH1750_I2C_PORT 0
#endif
#ifndef ESPAGENT_SECRET_BH1750_SCL_HZ
#define ESPAGENT_SECRET_BH1750_SCL_HZ   100000
#endif
#ifndef ESPAGENT_SECRET_BH1750_ADDR
#define ESPAGENT_SECRET_BH1750_ADDR     0x23
#endif
#ifndef ESPAGENT_SECRET_AHT10_SDA_GPIO
#define ESPAGENT_SECRET_AHT10_SDA_GPIO  21
#endif
#ifndef ESPAGENT_SECRET_AHT10_SCL_GPIO
#define ESPAGENT_SECRET_AHT10_SCL_GPIO  18
#endif
#ifndef ESPAGENT_SECRET_AHT10_I2C_PORT
#define ESPAGENT_SECRET_AHT10_I2C_PORT  0
#endif
#ifndef ESPAGENT_SECRET_AHT10_SCL_HZ
#define ESPAGENT_SECRET_AHT10_SCL_HZ    100000
#endif
#ifndef ESPAGENT_SECRET_AHT10_ADDR
#define ESPAGENT_SECRET_AHT10_ADDR      0x38
#endif
#ifndef ESPAGENT_SECRET_SERVO_GPIO
#define ESPAGENT_SECRET_SERVO_GPIO      5
#endif
#ifndef ESPAGENT_SECRET_DHT11_GPIO
#define ESPAGENT_SECRET_DHT11_GPIO      3
#endif
#ifndef ESPAGENT_SECRET_PRESENCE_GPIO
#define ESPAGENT_SECRET_PRESENCE_GPIO   13
#endif
#ifndef ESPAGENT_SECRET_HC_SR05_TRIG_GPIO
#define ESPAGENT_SECRET_HC_SR05_TRIG_GPIO (-1)
#endif
#ifndef ESPAGENT_SECRET_HC_SR05_ECHO_GPIO
#define ESPAGENT_SECRET_HC_SR05_ECHO_GPIO (-1)
#endif
#ifndef ESPAGENT_SECRET_HC_SR05_PRESENT_THRESHOLD_CM
#define ESPAGENT_SECRET_HC_SR05_PRESENT_THRESHOLD_CM 80
#endif
#ifndef ESPAGENT_SECRET_SENSOR_MQTT_BROKER
#define ESPAGENT_SECRET_SENSOR_MQTT_BROKER ""
#endif
#ifndef ESPAGENT_SECRET_SENSOR_MQTT_PORT
#define ESPAGENT_SECRET_SENSOR_MQTT_PORT 1883
#endif
#ifndef ESPAGENT_SECRET_SENSOR_DHT22_GPIO
#define ESPAGENT_SECRET_SENSOR_DHT22_GPIO 4
#endif
#ifndef ESPAGENT_SECRET_SENSOR_MHZ19_UART_NUM
#define ESPAGENT_SECRET_SENSOR_MHZ19_UART_NUM 1
#endif
#ifndef ESPAGENT_SECRET_SENSOR_MHZ19_RX_GPIO
#define ESPAGENT_SECRET_SENSOR_MHZ19_RX_GPIO 16
#endif
#ifndef ESPAGENT_SECRET_SENSOR_MHZ19_TX_GPIO
#define ESPAGENT_SECRET_SENSOR_MHZ19_TX_GPIO 17
#endif
#ifndef ESPAGENT_SECRET_SENSOR_MQTT_PUBLISH_INTERVAL_MS
#define ESPAGENT_SECRET_SENSOR_MQTT_PUBLISH_INTERVAL_MS 5000
#endif
#ifndef ESPAGENT_SECRET_NODE_ID
#define ESPAGENT_SECRET_NODE_ID "esp32s3-edge-01"
#endif
#ifndef ESPAGENT_SECRET_NODE_ROLE
#define ESPAGENT_SECRET_NODE_ROLE "edge_agent"
#endif
#ifndef ESPAGENT_SECRET_NODE_LOCATION
#define ESPAGENT_SECRET_NODE_LOCATION ESPAGENT_SECRET_AMAP_DEFAULT_LOCATION
#endif
#ifndef ESPAGENT_SECRET_MESH_TOPIC_PREFIX
#define ESPAGENT_SECRET_MESH_TOPIC_PREFIX "espagent"
#endif
#ifndef ESPAGENT_SECRET_NODE_CAPABILITIES
#define ESPAGENT_SECRET_NODE_CAPABILITIES "coordinator,communication,sensor,control,guardian,telemetry,timeline,alerts"
#endif
#ifndef ESPAGENT_SECRET_NODE_RESPONSIBILITIES
#define ESPAGENT_SECRET_NODE_RESPONSIBILITIES "single-node development profile; can chat, sense, control, publish telemetry, and audit mesh state"
#endif

/* WiFi */
#define ESPAGENT_WIFI_MAX_RETRY          10
#define ESPAGENT_WIFI_RETRY_BASE_MS      1000
#define ESPAGENT_WIFI_RETRY_MAX_MS       30000

/* Feishu Bot */
#define ESPAGENT_FEISHU_MAX_MSG_LEN          4096
#define ESPAGENT_FEISHU_POLL_STACK           (12 * 1024)
#define ESPAGENT_FEISHU_ACK_STACK            (8 * 1024)
#define ESPAGENT_FEISHU_POLL_PRIO            5
#define ESPAGENT_FEISHU_POLL_CORE            0
#define ESPAGENT_FEISHU_WEBHOOK_PORT         18790
#define ESPAGENT_FEISHU_WEBHOOK_PATH         "/feishu/events"
#define ESPAGENT_FEISHU_WEBHOOK_MAX_BODY     (16 * 1024)

/* Agent Loop */
#define ESPAGENT_AGENT_STACK             (24 * 1024)
#define ESPAGENT_AGENT_PRIO              6
#define ESPAGENT_AGENT_CORE              1
#define ESPAGENT_AGENT_MAX_HISTORY       20
#define ESPAGENT_AGENT_MAX_TOOL_ITER     10
#define ESPAGENT_MAX_TOOL_CALLS          4
#define ESPAGENT_AGENT_SEND_WORKING_STATUS 1

/* Subagent tool */
#define ESPAGENT_SUBAGENT_STACK          (12 * 1024)
#define ESPAGENT_SUBAGENT_PRIO           5
#define ESPAGENT_SUBAGENT_CORE           1
#define ESPAGENT_SUBAGENT_TIMEOUT_MS     (120 * 1000)
#define ESPAGENT_SUBAGENT_MAX_TOOL_ITER  5
#define ESPAGENT_SUBAGENT_CONTEXT_SIZE   (16 * 1024)
#define ESPAGENT_SUBAGENT_TOOL_BUF_SIZE  (8 * 1024)

/* Timezone (POSIX TZ format) */
#define ESPAGENT_TIMEZONE                "CST-8"
#define ESPAGENT_SNTP_SERVER             "ntp.aliyun.com"
#define ESPAGENT_SNTP_SYNC_WAIT_MS       10000
#define ESPAGENT_TIME_VALID_AFTER_EPOCH  1700000000
#define ESPAGENT_TIME_HTTP_HOST          "www.baidu.com"
#define ESPAGENT_TIME_HTTP_URL           "https://www.baidu.com/"

/* LLM */
#define ESPAGENT_LLM_DEFAULT_MODEL       "claude-opus-4-5"
#define ESPAGENT_LLM_PROVIDER_DEFAULT    "anthropic"
#define ESPAGENT_LLM_MAX_TOKENS          4096
#define ESPAGENT_LLM_API_URL             "https://api.anthropic.com/v1/messages"
#define ESPAGENT_OPENAI_API_URL          "https://api.deepseek.com/chat/completions"
#define ESPAGENT_LLM_API_VERSION         "2023-06-01"
#define ESPAGENT_LLM_STREAM_BUF_SIZE     (32 * 1024)
#define ESPAGENT_LLM_LOG_VERBOSE_PAYLOAD 0
#define ESPAGENT_LLM_LOG_PREVIEW_BYTES   160

/* Message Bus */
#define ESPAGENT_BUS_QUEUE_LEN           16
#define ESPAGENT_OUTBOUND_STACK          (12 * 1024)
#define ESPAGENT_OUTBOUND_PRIO           5
#define ESPAGENT_OUTBOUND_CORE           0

/* Memory / SPIFFS */
#define ESPAGENT_SPIFFS_BASE             "/spiffs"
#define ESPAGENT_SPIFFS_CONFIG_DIR       ESPAGENT_SPIFFS_BASE "/config"
#define ESPAGENT_SPIFFS_MEMORY_DIR       ESPAGENT_SPIFFS_BASE "/memory"
#define ESPAGENT_SPIFFS_SESSION_DIR      ESPAGENT_SPIFFS_BASE "/sessions"
#define ESPAGENT_MEMORY_FILE             ESPAGENT_SPIFFS_MEMORY_DIR "/MEMORY.md"
#define ESPAGENT_SOUL_FILE               ESPAGENT_SPIFFS_CONFIG_DIR "/SOUL.md"
#define ESPAGENT_USER_FILE               ESPAGENT_SPIFFS_CONFIG_DIR "/USER.md"
#define ESPAGENT_CONTEXT_BUF_SIZE        (24 * 1024)
#define ESPAGENT_SESSION_MAX_MSGS        20

/* Agent cache */
#define ESPAGENT_CACHE_MAX_ENTRIES       32
#define ESPAGENT_CACHE_MAX_KEY_BYTES     64
#define ESPAGENT_CACHE_MAX_VALUE_BYTES   4096
#define ESPAGENT_CACHE_MAX_TOTAL_BYTES   (24 * 1024)
#define ESPAGENT_CACHE_DEFAULT_TTL_S     300
#define ESPAGENT_CACHE_SKILLS_TTL_S      (24 * 60 * 60)

/* Cron / Heartbeat */
#define ESPAGENT_CRON_FILE               ESPAGENT_SPIFFS_BASE "/cron.json"
#define ESPAGENT_CRON_MAX_JOBS           16
#define ESPAGENT_CRON_CHECK_INTERVAL_MS  (60 * 1000)
#define ESPAGENT_HEARTBEAT_FILE          ESPAGENT_SPIFFS_BASE "/HEARTBEAT.md"
#define ESPAGENT_HEARTBEAT_INTERVAL_MS   (30 * 60 * 1000)

/* Automation Engine */
#define ESPAGENT_AUTOMATION_FILE         ESPAGENT_SPIFFS_BASE "/automation.json"
#define ESPAGENT_AUTOMATION_MAX_WORKFLOWS 8
#define ESPAGENT_AUTOMATION_MAX_RULES    8
#define ESPAGENT_AUTOMATION_WORKFLOW_MAX_STEPS 8
#define ESPAGENT_AUTOMATION_CHECK_INTERVAL_MS (5 * 1000)
#define ESPAGENT_AUTOMATION_STACK        (12 * 1024)

/* Proactive Agent */
#define ESPAGENT_PROACTIVE_ENABLED       1
#define ESPAGENT_PROACTIVE_STACK         (5 * 1024)
#define ESPAGENT_PROACTIVE_PRIO          4
#define ESPAGENT_PROACTIVE_INITIAL_DELAY_MS (10 * 60 * 1000)
#define ESPAGENT_PROACTIVE_INTERVAL_MS   (60 * 60 * 1000)
#define ESPAGENT_PROACTIVE_NO_MESSAGE    "PROACTIVE_NO_MESSAGE"

/* GPIO */
#define ESPAGENT_GPIO_CONFIG_SECTION     1   /* enable GPIO tools */

/* Skills */
#define ESPAGENT_SKILLS_PREFIX           ESPAGENT_SPIFFS_BASE "/skills/"

/* Amap weather */
#define ESPAGENT_AMAP_DEFAULT_LOCATION   ESPAGENT_SECRET_AMAP_DEFAULT_LOCATION
#define ESPAGENT_AMAP_DEFAULT_ADCODE     ESPAGENT_SECRET_AMAP_DEFAULT_ADCODE

/* LingShu Agent Mesh node identity */
#define ESPAGENT_NODE_ID                 ESPAGENT_SECRET_NODE_ID
#define ESPAGENT_NODE_ROLE               ESPAGENT_SECRET_NODE_ROLE
#define ESPAGENT_NODE_LOCATION           ESPAGENT_SECRET_NODE_LOCATION
#define ESPAGENT_MESH_TOPIC_PREFIX       ESPAGENT_SECRET_MESH_TOPIC_PREFIX
#define ESPAGENT_NODE_CAPABILITIES       ESPAGENT_SECRET_NODE_CAPABILITIES
#define ESPAGENT_NODE_RESPONSIBILITIES   ESPAGENT_SECRET_NODE_RESPONSIBILITIES

/* Hardware IO */
#define ESPAGENT_WS2812_DEFAULT_GPIO     ESPAGENT_SECRET_WS2812_GPIO
#define ESPAGENT_SGP30_DEFAULT_SDA_GPIO  ESPAGENT_SECRET_SGP30_SDA_GPIO
#define ESPAGENT_SGP30_DEFAULT_SCL_GPIO  ESPAGENT_SECRET_SGP30_SCL_GPIO
#define ESPAGENT_SGP30_DEFAULT_I2C_PORT  ESPAGENT_SECRET_SGP30_I2C_PORT
#define ESPAGENT_SGP30_DEFAULT_SCL_HZ    ESPAGENT_SECRET_SGP30_SCL_HZ
#define ESPAGENT_MAX98357_DEFAULT_BCLK_GPIO ESPAGENT_SECRET_MAX98357_BCLK_GPIO
#define ESPAGENT_MAX98357_DEFAULT_WS_GPIO   ESPAGENT_SECRET_MAX98357_WS_GPIO
#define ESPAGENT_MAX98357_DEFAULT_DIN_GPIO  ESPAGENT_SECRET_MAX98357_DIN_GPIO
#define ESPAGENT_MAX98357_DEFAULT_SD_GPIO   ESPAGENT_SECRET_MAX98357_SD_GPIO
#define ESPAGENT_MAX98357_DEFAULT_I2S_PORT  ESPAGENT_SECRET_MAX98357_I2S_PORT
#define ESPAGENT_MAX98357_DEFAULT_SAMPLE_RATE_HZ ESPAGENT_SECRET_MAX98357_SAMPLE_RATE_HZ
#define ESPAGENT_MAX98357_DEFAULT_TONE_HZ   ESPAGENT_SECRET_MAX98357_DEFAULT_TONE_HZ
#define ESPAGENT_MAX98357_DEFAULT_DURATION_MS ESPAGENT_SECRET_MAX98357_DEFAULT_DURATION_MS
#define ESPAGENT_MAX98357_DEFAULT_VOLUME_PCT ESPAGENT_SECRET_MAX98357_DEFAULT_VOLUME_PCT
#define ESPAGENT_BH1750_DEFAULT_SDA_GPIO ESPAGENT_SECRET_BH1750_SDA_GPIO
#define ESPAGENT_BH1750_DEFAULT_SCL_GPIO ESPAGENT_SECRET_BH1750_SCL_GPIO
#define ESPAGENT_BH1750_DEFAULT_I2C_PORT ESPAGENT_SECRET_BH1750_I2C_PORT
#define ESPAGENT_BH1750_DEFAULT_SCL_HZ   ESPAGENT_SECRET_BH1750_SCL_HZ
#define ESPAGENT_BH1750_DEFAULT_ADDR     ESPAGENT_SECRET_BH1750_ADDR
#define ESPAGENT_AHT10_DEFAULT_SDA_GPIO  ESPAGENT_SECRET_AHT10_SDA_GPIO
#define ESPAGENT_AHT10_DEFAULT_SCL_GPIO  ESPAGENT_SECRET_AHT10_SCL_GPIO
#define ESPAGENT_AHT10_DEFAULT_I2C_PORT  ESPAGENT_SECRET_AHT10_I2C_PORT
#define ESPAGENT_AHT10_DEFAULT_SCL_HZ    ESPAGENT_SECRET_AHT10_SCL_HZ
#define ESPAGENT_AHT10_DEFAULT_ADDR      ESPAGENT_SECRET_AHT10_ADDR
#define ESPAGENT_SGP30_MONITOR_STACK     (4 * 1024)
#define ESPAGENT_SGP30_MONITOR_PRIO      4
#define ESPAGENT_SGP30_MONITOR_CORE      0
#define ESPAGENT_SGP30_MONITOR_INTERVAL_MS 1000
#define ESPAGENT_SGP30_MONITOR_RETRY_MS    5000

/* Servo */
#define ESPAGENT_SERVO_DEFAULT_GPIO     ESPAGENT_SECRET_SERVO_GPIO
#define ESPAGENT_SERVO_MIN_PULSE_US      500
#define ESPAGENT_SERVO_MAX_PULSE_US      2500
#define ESPAGENT_SERVO_FREQ_HZ           50

/* DHT11 temperature/humidity sensor (legacy) */
#define ESPAGENT_DHT11_DEFAULT_GPIO      ESPAGENT_SECRET_DHT11_GPIO

/* 3-wire digital human presence/PIR sensor */
#define ESPAGENT_PRESENCE_DEFAULT_GPIO   ESPAGENT_SECRET_PRESENCE_GPIO

/* HC-SR05 ultrasonic presence/proximity sensor */
#define ESPAGENT_HC_SR05_DEFAULT_TRIG_GPIO ESPAGENT_SECRET_HC_SR05_TRIG_GPIO
#define ESPAGENT_HC_SR05_DEFAULT_ECHO_GPIO ESPAGENT_SECRET_HC_SR05_ECHO_GPIO
#define ESPAGENT_HC_SR05_PRESENT_THRESHOLD_CM ESPAGENT_SECRET_HC_SR05_PRESENT_THRESHOLD_CM

/* RPi MQTT sensor pipe */
#define ESPAGENT_SENSOR_MQTT_BROKER      ESPAGENT_SECRET_SENSOR_MQTT_BROKER
#define ESPAGENT_SENSOR_MQTT_PORT        ESPAGENT_SECRET_SENSOR_MQTT_PORT
#define ESPAGENT_SENSOR_MQTT_TOPIC_TELEMETRY ESPAGENT_MESH_TOPIC_PREFIX "/nodes/" ESPAGENT_NODE_ID "/telemetry"
#define ESPAGENT_SENSOR_MQTT_TOPIC_STATE     ESPAGENT_MESH_TOPIC_PREFIX "/nodes/" ESPAGENT_NODE_ID "/state"
#define ESPAGENT_SENSOR_MQTT_TOPIC_EVENTS    ESPAGENT_MESH_TOPIC_PREFIX "/nodes/" ESPAGENT_NODE_ID "/events"
#define ESPAGENT_SENSOR_MQTT_TOPIC_COMMAND   ESPAGENT_MESH_TOPIC_PREFIX "/nodes/" ESPAGENT_NODE_ID "/command"
#define ESPAGENT_MESH_TOPIC_ROLE_COMMAND     ESPAGENT_MESH_TOPIC_PREFIX "/roles/" ESPAGENT_NODE_ROLE "/command"
#define ESPAGENT_MESH_TOPIC_DISPATCH         ESPAGENT_MESH_TOPIC_PREFIX "/agent/dispatch"
#define ESPAGENT_MESH_TOPIC_TIMELINE         ESPAGENT_MESH_TOPIC_PREFIX "/agent/timeline"
#define ESPAGENT_MESH_TOPIC_ALERTS           ESPAGENT_MESH_TOPIC_PREFIX "/alerts"
#define ESPAGENT_MESH_TOPIC_POLICY_CHECK     ESPAGENT_MESH_TOPIC_PREFIX "/security/policy_check"
#define ESPAGENT_MESH_TOPIC_POLICY_DECISION  ESPAGENT_MESH_TOPIC_PREFIX "/security/decision"
#define ESPAGENT_MESH_TOPIC_GUARDIAN_STATEBOARD ESPAGENT_MESH_TOPIC_PREFIX "/guardian/stateboard"
#define ESPAGENT_SENSOR_MQTT_TOPIC_DATA      ESPAGENT_SENSOR_MQTT_TOPIC_TELEMETRY
#define ESPAGENT_SENSOR_MQTT_TOPIC_ANALYSIS  ESPAGENT_MESH_TOPIC_DISPATCH
#define ESPAGENT_SENSOR_MQTT_TOPIC_ALERT     ESPAGENT_MESH_TOPIC_ALERTS
#define ESPAGENT_SENSOR_MQTT_PUBLISH_INTERVAL_MS ESPAGENT_SECRET_SENSOR_MQTT_PUBLISH_INTERVAL_MS
#define ESPAGENT_SENSOR_MQTT_STACK       (5 * 1024)
#define ESPAGENT_SENSOR_MQTT_PRIO        4
#define ESPAGENT_SENSOR_MQTT_CORE        0
#define ESPAGENT_SENSOR_DHT22_GPIO       ESPAGENT_SECRET_SENSOR_DHT22_GPIO
#define ESPAGENT_SENSOR_MHZ19_UART_NUM   ESPAGENT_SECRET_SENSOR_MHZ19_UART_NUM
#define ESPAGENT_SENSOR_MHZ19_RX_GPIO    ESPAGENT_SECRET_SENSOR_MHZ19_RX_GPIO
#define ESPAGENT_SENSOR_MHZ19_TX_GPIO    ESPAGENT_SECRET_SENSOR_MHZ19_TX_GPIO

/* WebSocket Gateway */
#define ESPAGENT_WS_PORT                 18789
#define ESPAGENT_WS_MAX_CLIENTS          4

/* Serial CLI */
#define ESPAGENT_CLI_STACK               (12 * 1024)
#define ESPAGENT_CLI_PRIO                3
#define ESPAGENT_CLI_CORE                0

/* NVS Namespaces */
#define ESPAGENT_NVS_WIFI                "wifi_config"
#define ESPAGENT_NVS_FEISHU              "feishu_config"
#define ESPAGENT_NVS_LLM                 "llm_config"
#define ESPAGENT_NVS_PROXY               "proxy_config"
#define ESPAGENT_NVS_SEARCH              "search_config"
#define ESPAGENT_NVS_PROACTIVE           "proactive_config"
#define ESPAGENT_NVS_AMAP                "amap_config"
#define ESPAGENT_NVS_NODE                "node_config"

/* NVS Keys */
#define ESPAGENT_NVS_KEY_SSID            "ssid"
#define ESPAGENT_NVS_KEY_PASS            "password"
#define ESPAGENT_NVS_KEY_FEISHU_APP_ID   "app_id"
#define ESPAGENT_NVS_KEY_FEISHU_APP_SECRET "app_secret"
#define ESPAGENT_NVS_KEY_API_KEY         "api_key"
#define ESPAGENT_NVS_KEY_TAVILY_KEY      "tavily_key"
#define ESPAGENT_NVS_KEY_MODEL           "model"
#define ESPAGENT_NVS_KEY_PROVIDER        "provider"
#define ESPAGENT_NVS_KEY_PROXY_HOST      "host"
#define ESPAGENT_NVS_KEY_PROXY_PORT      "port"
#define ESPAGENT_NVS_KEY_PROXY_TYPE      "proxy_type"
#define ESPAGENT_NVS_KEY_CHANNEL         "channel"
#define ESPAGENT_NVS_KEY_CHAT_ID         "chat_id"
#define ESPAGENT_NVS_KEY_LOCATION        "location"
#define ESPAGENT_NVS_KEY_ADCODE          "adcode"
#define ESPAGENT_NVS_KEY_NODE_ID         "node_id"
#define ESPAGENT_NVS_KEY_NODE_ROLE       "node_role"
#define ESPAGENT_NVS_KEY_NODE_LOCATION   "node_location"
#define ESPAGENT_NVS_KEY_NODE_CAPABILITIES "node_capabilities"
#define ESPAGENT_NVS_KEY_NODE_RESPONSIBILITIES "node_responsibilities"

/* WiFi Onboarding (Captive Portal) */
#define ESPAGENT_ONBOARD_AP_PREFIX    "ESPAgent-"
#define ESPAGENT_ONBOARD_AP_PASS      ""          /* open network */
#define ESPAGENT_ONBOARD_HTTP_PORT    80
#define ESPAGENT_ONBOARD_DNS_STACK    (4 * 1024)
#define ESPAGENT_ONBOARD_MAX_SCAN     20
#ifndef ESPAGENT_ONBOARD_ADMIN_AFTER_WIFI
#define ESPAGENT_ONBOARD_ADMIN_AFTER_WIFI 0       /* keep STA-only during normal agent runtime */
#endif
